### PR TITLE
Fix typo and grammar

### PR DESCRIPTION
**Pull request by surajgautam**
Hello There,

At the time of going through openvidu documentation, I found few typos and grammatical errors. I have updated the changes.

### CODE REVIEW

**Comment by surajgautam** [comment]
@micaelgallego @nordri Can anyone please review this PR?

**Comment by nordri** [comment]
Sorry @surajgautam I'm not a member of this project any more.

**Comment by surajgautam** [comment]
@guettli @adambyer @micaelgallego

**Comment by surajgautam** [comment]
@CSantosM please have  a look into this.

**Pull request merged**
